Remove some non null assertion operator
TypeCellOS/BlockNote pull request #1057
Opened 2024-09-07 01:41 UTC by kody-liou

2024-09-07 01:45 UTC, kody-liou commented on package.json
> +    "prepare": "npm run clean && npm run gen && npm run clean && lerna run --stream build --concurrency 1",
I added the prepare script and installed BlockNote from my GitHub repository. Here's an example:

```json
  "dependencies": {
    "@blocknote/core": "git+https://github.com/kody-liou/BlockNote.git#Remove-some-non-null-assertion-operator",
    "@blocknote/mantine": "git+https://github.com/kody-liou/BlockNote.git#Remove-some-non-null-assertion-operator",
    "@blocknote/react": "git+https://github.com/kody-liou/BlockNote.git#Remove-some-non-null-assertion-operator",
   }
```
However, it throws an error:
 ```
 9:37:59 AM [vite] Internal server error: Failed to resolve import "@blocknote/core/fonts/inter.css" from "src/renderer/src/pages/home.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/_src/personal/note-nook/src/renderer/src/pages/home.tsx:15:7
  30 |  import { useLocation } from "wouter";
  31 |  import { TagNavigator, Tags, useTagHook } from "@renderer/components/tag-navigator";
  32 |  import "@blocknote/core/fonts/inter.css";
     |          ^
  33 |  import "@blocknote/mantine/style.css";
  34 |  import { Editor, useEditorHook } from "../components/editor";
      at formatError (file:///D:/_src/personal/note-nook/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:52009:46)
      at TransformContext.error (file:///D:/_src/personal/note-nook/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:52003:19)
      at normalizeUrl (file:///D:/_src/personal/note-nook/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:67306:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///D:/_src/personal/note-nook/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:67461:47
      at async Promise.all (index 8)
      at async TransformContext.transform (file:///D:/_src/personal/note-nook/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:67382:13)
      at async Object.transform (file:///D:/_src/personal/note-nook/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:52318:30)
      at async loadAndTransform (file:///D:/_src/personal/note-nook/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:55073:29)
      at async viteTransformMiddleware (file:///D:/_src/personal/note-nook/node_modules/.pnpm/vite@5.2.13_@types+node@20.14.2/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:64920:32)
dep-DEPSZ3SS.js:13348
 ```

2024-09-09 15:17 UTC, matthewlipski requested changes
The non-null assertion changes look good, but what's up with the version bump? I assume it's smth to do with the `prepare` script so do you could just keep the non-null fixes in this PR and create a new issue/PR for the script?

2024-09-11 14:15 UTC, kody-liu commented
Done. I’ve removed the prepare script and the version bump. This PR now only includes the non-null assertion changes.

2024-09-12 14:33 UTC, matthewlipski commented
Awesome thx!

2024-09-18 21:33 UTC, merged