fix: File resize UX
TypeCellOS/BlockNote pull request #1223
Opened 2024-11-07 13:05 UTC by matthewlipski

This PR fixes 2 bugs regarding file resize UX:

1. File blocks with captions have incorrect width when caption is longer than the editor is wide (see Default Schema Showcase demo with a narrow browser window).
2. Resizing file blocks with captions only resizes the caption once the mouse button is released, yet the file preview is resized while moving the mouse.
3. Blocks which have an initial width wider than the editor don't get resized on the first attempt.

2024-11-14 13:03 UTC, YousefED requested changes
I'm a bit concerned about this approach, see comment!

2024-11-14 13:03 UTC, YousefED commented on packages/core/src/blocks/ImageBlockContent/ImageBlockContent.ts
> +  if (
My first feeling is I don't really like this approach:
- what if a user opens the document on a small screen, and later on a large screen?
- what if the user is in read-only mode?

2024-11-14 13:03 UTC, YousefED commented on packages/core/src/editor/Block.css
> +[data-file-block] .bn-resize-handles-wrapper {
make sure DO etc isn't using the old classnames. I suppose you didn't like the earlier name / just a cleanup right?

2024-12-05 19:25 UTC, matthewlipski commented
Closing in favor of #1305

2024-12-05 19:25 UTC, closed without merging