Dark theme
TypeCellOS/BlockNote pull request #171
Opened 2023-04-17 22:00 UTC by matthewlipski

This PR adds a dark theme to BlockNote which you can toggle using the `useDarkTheme` editor option. Looks pretty good but has a few issues:

1. The hack we used to fix the color picker sets a white background on hover, and we don't have a way of easily accessing the `useDarkTheme` option to change this. I think this may be fixed in PR #143.
2. The actual editor is not currently themed as it is part of the `core` package, while the dark theme at least partially relies on Mantine which is only used for UI in the `react` package.

Theming with Mantine is actually a bit of a pain since we customize the layouts quite a bit and have to change the colours of those manually. At some point when we want to focus more on UI design it might be worth just making a custom UI instead of relying on premade Mantine components.

2023-04-18 05:07 UTC, YousefED requested changes
Nice. I left some inline comments. Also:

**editor content styling**
> 2. The actual editor is not currently themed as it is part of the core package, while the dark theme at least partially relies on Mantine which is only used for UI in the react package.

The core package should be responsible for styling the actual editor content right? The contents of the editor now remains black text on white bg, that should also be changed

**website dark mode**
I've pushed a commit that enables dark mode on the website so we can properly showcase the dark-mode compatibality 😄. This brings up a few new issues:
- We need to update the theme at run time (there's a TODO left in code where we can do this).
- Some elements of the website will need to come with a dark + light variant. I've already done this for the logo + "try this" elements. We'll need to update the screenshots
- Ideally, the examples in the documentation are also theme-aware

2023-04-18 12:02 UTC, matthewlipski commented
> Nice. I left some inline comments. Also:
> 
> **editor content styling**
> 
> > 2. The actual editor is not currently themed as it is part of the core package, while the dark theme at least partially relies on Mantine which is only used for UI in the react package.
> 
> The core package should be responsible for styling the actual editor content right? The contents of the editor now remains black text on white bg, that should also be changed
> 
> **website dark mode** I've pushed a commit that enables dark mode on the website so we can properly showcase the dark-mode compatibality 😄. This brings up a few new issues:
> 
> * We need to update the theme at run time (there's a TODO left in code where we can do this).
> * Some elements of the website will need to come with a dark + light variant. I've already done this for the logo + "try this" elements. We'll need to update the screenshots
> * Ideally, the examples in the documentation are also theme-aware

One thing about the editor dark mode is since we're only using basic CSS in `core` we have to hard code the text and background colors instead of taking them from `blockNoteColorTheme` like we do for the menus. Do you think that's ok for now?

2023-04-18 12:58 UTC, YousefED commented
> One thing about the editor dark mode is since we're only using basic CSS in core we have to hard code the text and background colors instead of taking them from blockNoteColorTheme like we do for the menus. Do you think that's ok for now?

Yes that's ok for now (i.e.: use a .dark class on the container). We can come up with other solutions as well to set these colors dynamically (e.g.: css vars), but I think now it's ok

2023-04-18 13:51 UTC, matthewlipski commented
> Nice. I left some inline comments. Also:
> 
> **editor content styling**
> 
> > 2. The actual editor is not currently themed as it is part of the core package, while the dark theme at least partially relies on Mantine which is only used for UI in the react package.
> 
> The core package should be responsible for styling the actual editor content right? The contents of the editor now remains black text on white bg, that should also be changed
> 
> **website dark mode** I've pushed a commit that enables dark mode on the website so we can properly showcase the dark-mode compatibality 😄. This brings up a few new issues:
> 
> * We need to update the theme at run time (there's a TODO left in code where we can do this).
> * Some elements of the website will need to come with a dark + light variant. I've already done this for the logo + "try this" elements. We'll need to update the screenshots
> * Ideally, the examples in the documentation are also theme-aware

Also, do we want to sort out the website dark mode in this PR? Imo should be on a separate branch since it seems like dark mode for the editor is highly requested and I think shouldn't break anything for the website, maybe just look a bit ugly if we have a dark mode example.

2023-04-18 17:49 UTC, YousefED commented on packages/core/src/extensions/Blocks/nodes/Block.module.css
> +/* TODO: Should be different for light/dark editor class, but can't check since
Maybe we can:
- use a regular "dark" class on the editor? (instead of via modules)
- set data-theme="dark" on the editor?

2023-04-20 11:22 UTC, YousefED approved these changes

2023-04-20 11:25 UTC, merged