fix: UI element position on scroll
TypeCellOS/BlockNote pull request #769
Opened 2024-05-27 16:59 UTC by matthewlipski

This PR fixes UI elements like the formatting toolbar and side menu only scrolling with the editor when the whole page is being scrolled. Now, the elements scroll with the editor regardless of which containing element is being scrolled. Additionally, the side menu is now hidden on click after being frozen, to more closely replicate Notion's UX.

Closes #748

2024-05-27 18:05 UTC, YousefED approved these changes

2024-05-29 20:29 UTC, bensku commented
Not sure if I'm doing something wrong, but I can't get the side menu to open again in preview of this PR after I've closed it. Clicking or hovering over where it should be doesn't seem to work.

#648 seems to be fixed, though.

2024-06-03 11:40 UTC, YousefED requested changes
Thanks for testing @bensku !

Confirmed there's some bug here:
![bug side](https://github.com/TypeCellOS/BlockNote/assets/368857/8fe5b4f7-0fd8-4610-93b8-af2e72be2fed)

2024-06-04 16:59 UTC, matthewlipski commented
> Thanks for testing @bensku !
> 
> Confirmed there's some bug here: ![bug side](https://private-user-images.githubusercontent.com/368857/336055449-8fe5b4f7-0fd8-4610-93b8-af2e72be2fed.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MjAwMzMsIm5iZiI6MTcxNzUxOTczMywicGF0aCI6Ii8zNjg4NTcvMzM2MDU1NDQ5LThmZTViNGY3LTBmZDgtNDYxMC05M2I4LWFmMmU3MmJlMmZlZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxNjQ4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzgzNmQ5ZjNmMWM2MGY4NDJjOGZkMGJkYWQ2NmQ5OWE5ZjIzNzE4MGI1MzBkMzI5OGE0MGI2YmUzMGMyNzg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T92DSCUPl1oHCkDHpavVFYwM3YBotoqtDMa6XVGPso8) [ ![bug side](https://private-user-images.githubusercontent.com/368857/336055449-8fe5b4f7-0fd8-4610-93b8-af2e72be2fed.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MjAwMzMsIm5iZiI6MTcxNzUxOTczMywicGF0aCI6Ii8zNjg4NTcvMzM2MDU1NDQ5LThmZTViNGY3LTBmZDgtNDYxMC05M2I4LWFmMmU3MmJlMmZlZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxNjQ4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzgzNmQ5ZjNmMWM2MGY4NDJjOGZkMGJkYWQ2NmQ5OWE5ZjIzNzE4MGI1MzBkMzI5OGE0MGI2YmUzMGMyNzg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T92DSCUPl1oHCkDHpavVFYwM3YBotoqtDMa6XVGPso8) ](https://private-user-images.githubusercontent.com/368857/336055449-8fe5b4f7-0fd8-4610-93b8-af2e72be2fed.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MjAwMzMsIm5iZiI6MTcxNzUxOTczMywicGF0aCI6Ii8zNjg4NTcvMzM2MDU1NDQ5LThmZTViNGY3LTBmZDgtNDYxMC05M2I4LWFmMmU3MmJlMmZlZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxNjQ4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzgzNmQ5ZjNmMWM2MGY4NDJjOGZkMGJkYWQ2NmQ5OWE5ZjIzNzE4MGI1MzBkMzI5OGE0MGI2YmUzMGMyNzg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T92DSCUPl1oHCkDHpavVFYwM3YBotoqtDMa6XVGPso8) [ ](https://private-user-images.githubusercontent.com/368857/336055449-8fe5b4f7-0fd8-4610-93b8-af2e72be2fed.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MjAwMzMsIm5iZiI6MTcxNzUxOTczMywicGF0aCI6Ii8zNjg4NTcvMzM2MDU1NDQ5LThmZTViNGY3LTBmZDgtNDYxMC05M2I4LWFmMmU3MmJlMmZlZC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQxNjQ4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNzgzNmQ5ZjNmMWM2MGY4NDJjOGZkMGJkYWQ2NmQ5OWE5ZjIzNzE4MGI1MzBkMzI5OGE0MGI2YmUzMGMyNzg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T92DSCUPl1oHCkDHpavVFYwM3YBotoqtDMa6XVGPso8)

Fixed! Also I checked Notion and looks like their UX in general hides the side menu whenever the slash menu is open. We had this before only when using the add block button, but not when opening the slash menu using the "/" key, which made our own UX was kind of inconsistent. I made it so that opening the slash menu initially hides the side menu but moving the mouse shows it again (now the same for both pressing "/" key and add block button)

I think we can into making BlockNote's behaviour the same as Notions for this case (i.e. the side menu stays hidden while the slash menu is open), but that's a separate issue.

2024-06-05 07:31 UTC, YousefED approved these changes

2024-06-05 16:09 UTC, merged